/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'paymentStatus' : string,
  'customerPhone' : string,
  'guestCount' : bigint,
  'createdAt' : Time,
  'menuSelections' : Array<bigint>,
  'notes' : string,
  'advancePaid' : bigint,
  'balanceDue' : bigint,
  'customerId' : [] | [Principal],
  'hallId' : bigint,
  'branchId' : bigint,
  'customerEmail' : string,
  'eventDate' : Time,
  'quotationAmount' : bigint,
  'eventType' : string,
}
export interface BookingVendor { 'bookingId' : bigint, 'vendorId' : bigint }
export interface Branch {
  'id' : bigint,
  'name' : string,
  'phone' : string,
  'location' : string,
  'managerName' : string,
}
export interface ChecklistItem {
  'id' : bigint,
  'bookingId' : bigint,
  'assignedTo' : bigint,
  'task' : string,
  'isDone' : boolean,
}
export interface Feedback {
  'id' : bigint,
  'customerName' : string,
  'bookingId' : bigint,
  'submittedAt' : Time,
  'comment' : string,
  'rating' : bigint,
}
export interface Hall {
  'id' : bigint,
  'name' : string,
  'pricePerHead' : bigint,
  'description' : string,
  'availableSeats' : bigint,
  'capacity' : bigint,
  'branchId' : bigint,
}
export interface Invoice {
  'id' : bigint,
  'bookingId' : bigint,
  'generatedAt' : Time,
  'isPaid' : boolean,
  'totalAmount' : bigint,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem { 'description' : string, 'amount' : bigint }
export interface Lead {
  'id' : bigint,
  'status' : string,
  'assignedTo' : bigint,
  'interestedHallId' : bigint,
  'name' : string,
  'visitDate' : Time,
  'email' : string,
  'notes' : string,
  'phone' : string,
  'eventType' : string,
}
export interface MenuCategory { 'name' : string, 'description' : string }
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isVegetarian' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface Payment {
  'id' : bigint,
  'method' : string,
  'bookingId' : bigint,
  'notes' : string,
  'paymentDate' : Time,
  'paymentType' : string,
  'amount' : bigint,
}
export interface Staff {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
  'branchId' : bigint,
}
export interface Stock {
  'id' : bigint,
  'unit' : string,
  'quantityOnHand' : bigint,
  'itemName' : string,
  'minimumThreshold' : bigint,
  'branchId' : bigint,
}
export interface StockRequest {
  'id' : bigint,
  'status' : string,
  'createdAt' : Time,
  'quantityRequested' : bigint,
  'itemName' : string,
  'branchId' : bigint,
  'requestedBy' : bigint,
  'resolvedAt' : [] | [Time],
  'reason' : string,
}
export interface StockUsage {
  'id' : bigint,
  'bookingId' : bigint,
  'stockItemId' : bigint,
  'recordedAt' : Time,
  'quantityUsed' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
  'branchId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'branchId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookingVendor' : ActorMethod<[bigint, bigint], undefined>,
  'approveStockRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      Time,
      bigint,
      Array<bigint>,
      string,
    ],
    bigint
  >,
  'createBranch' : ActorMethod<[string, string, string, string], bigint>,
  'createChecklistItem' : ActorMethod<[bigint, string, bigint], bigint>,
  'createHall' : ActorMethod<
    [bigint, string, bigint, bigint, string, bigint],
    bigint
  >,
  'createInvoice' : ActorMethod<[bigint, Array<InvoiceItem>, bigint], bigint>,
  'createLead' : ActorMethod<
    [string, string, string, string, bigint, Time, string, bigint],
    bigint
  >,
  'createMenuCategory' : ActorMethod<[string, string], undefined>,
  'createMenuItem' : ActorMethod<
    [string, string, string, bigint, boolean],
    bigint
  >,
  'createStaff' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'createStock' : ActorMethod<[bigint, string, string, bigint, bigint], bigint>,
  'createStockRequest' : ActorMethod<
    [bigint, bigint, string, bigint, string],
    bigint
  >,
  'createVendor' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'deleteBranch' : ActorMethod<[bigint], undefined>,
  'deleteChecklistItem' : ActorMethod<[bigint], undefined>,
  'deleteHall' : ActorMethod<[bigint], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteStaff' : ActorMethod<[bigint], undefined>,
  'deleteStock' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllBranches' : ActorMethod<[], Array<Branch>>,
  'getAllChecklistItems' : ActorMethod<[], Array<ChecklistItem>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllHalls' : ActorMethod<[], Array<Hall>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllMenuCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getAllStock' : ActorMethod<[], Array<Stock>>,
  'getAllStockRequests' : ActorMethod<[], Array<StockRequest>>,
  'getAllStockUsage' : ActorMethod<[], Array<StockUsage>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingVendors' : ActorMethod<[bigint], Array<BookingVendor>>,
  'getBranch' : ActorMethod<[bigint], Branch>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChecklistItem' : ActorMethod<[bigint], ChecklistItem>,
  'getFeedback' : ActorMethod<[bigint], Feedback>,
  'getHall' : ActorMethod<[bigint], Hall>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getLead' : ActorMethod<[bigint], Lead>,
  'getMenuCategory' : ActorMethod<[string], MenuCategory>,
  'getMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getPayment' : ActorMethod<[bigint], Payment>,
  'getStaff' : ActorMethod<[bigint], Staff>,
  'getStock' : ActorMethod<[bigint], Stock>,
  'getStockRequest' : ActorMethod<[bigint], StockRequest>,
  'getStockUsage' : ActorMethod<[bigint], StockUsage>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendor' : ActorMethod<[bigint], Vendor>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<
    [bigint, bigint, string, string, string],
    bigint
  >,
  'recordStockUsage' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedback' : ActorMethod<[bigint, string, bigint, string], bigint>,
  'updateBooking' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      Time,
      bigint,
      Array<bigint>,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
    ],
    undefined
  >,
  'updateBranch' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateChecklistItem' : ActorMethod<
    [bigint, string, boolean, bigint],
    undefined
  >,
  'updateHall' : ActorMethod<
    [bigint, bigint, string, bigint, bigint, string, bigint],
    undefined
  >,
  'updateLead' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      Time,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, string, bigint, boolean],
    undefined
  >,
  'updateStaff' : ActorMethod<
    [bigint, string, string, bigint, string, string, boolean],
    undefined
  >,
  'updateStock' : ActorMethod<
    [bigint, bigint, string, string, bigint, bigint],
    undefined
  >,
  'updateVendor' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];