/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const InvoiceItem = IDL.Record({
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'customerPhone' : IDL.Text,
  'guestCount' : IDL.Nat,
  'createdAt' : Time,
  'menuSelections' : IDL.Vec(IDL.Nat),
  'notes' : IDL.Text,
  'advancePaid' : IDL.Nat,
  'balanceDue' : IDL.Nat,
  'customerId' : IDL.Opt(IDL.Principal),
  'hallId' : IDL.Nat,
  'branchId' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'eventDate' : Time,
  'quotationAmount' : IDL.Nat,
  'eventType' : IDL.Text,
});
export const Branch = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'managerName' : IDL.Text,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'assignedTo' : IDL.Nat,
  'task' : IDL.Text,
  'isDone' : IDL.Bool,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'bookingId' : IDL.Nat,
  'submittedAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Hall = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'pricePerHead' : IDL.Nat,
  'description' : IDL.Text,
  'availableSeats' : IDL.Nat,
  'capacity' : IDL.Nat,
  'branchId' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'generatedAt' : Time,
  'isPaid' : IDL.Bool,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(InvoiceItem),
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'assignedTo' : IDL.Nat,
  'interestedHallId' : IDL.Nat,
  'name' : IDL.Text,
  'visitDate' : Time,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'eventType' : IDL.Text,
});
export const MenuCategory = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isVegetarian' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'method' : IDL.Text,
  'bookingId' : IDL.Nat,
  'notes' : IDL.Text,
  'paymentDate' : Time,
  'paymentType' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Staff = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'branchId' : IDL.Nat,
});
export const Stock = IDL.Record({
  'id' : IDL.Nat,
  'unit' : IDL.Text,
  'quantityOnHand' : IDL.Nat,
  'itemName' : IDL.Text,
  'minimumThreshold' : IDL.Nat,
  'branchId' : IDL.Nat,
});
export const StockRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : Time,
  'quantityRequested' : IDL.Nat,
  'itemName' : IDL.Text,
  'branchId' : IDL.Nat,
  'requestedBy' : IDL.Nat,
  'resolvedAt' : IDL.Opt(Time),
  'reason' : IDL.Text,
});
export const StockUsage = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'stockItemId' : IDL.Nat,
  'recordedAt' : Time,
  'quantityUsed' : IDL.Nat,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'branchId' : IDL.Nat,
});
export const BookingVendor = IDL.Record({
  'bookingId' : IDL.Nat,
  'vendorId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'branchId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookingVendor' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveStockRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Nat,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createBranch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createChecklistItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createHall' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Nat, IDL.Vec(InvoiceItem), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createMenuCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createStaff' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createStock' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createStockRequest' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createVendor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [], []),
  'deleteChecklistItem' : IDL.Func([IDL.Nat], [], []),
  'deleteHall' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteStaff' : IDL.Func([IDL.Nat], [], []),
  'deleteStock' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getAllChecklistItems' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllHalls' : IDL.Func([], [IDL.Vec(Hall)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getAllStock' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
  'getAllStockRequests' : IDL.Func([], [IDL.Vec(StockRequest)], ['query']),
  'getAllStockUsage' : IDL.Func([], [IDL.Vec(StockUsage)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingVendors' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BookingVendor)],
      ['query'],
    ),
  'getBranch' : IDL.Func([IDL.Nat], [Branch], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChecklistItem' : IDL.Func([IDL.Nat], [ChecklistItem], ['query']),
  'getFeedback' : IDL.Func([IDL.Nat], [Feedback], ['query']),
  'getHall' : IDL.Func([IDL.Nat], [Hall], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getMenuCategory' : IDL.Func([IDL.Text], [MenuCategory], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
  'getStaff' : IDL.Func([IDL.Nat], [Staff], ['query']),
  'getStock' : IDL.Func([IDL.Nat], [Stock], ['query']),
  'getStockRequest' : IDL.Func([IDL.Nat], [StockRequest], ['query']),
  'getStockUsage' : IDL.Func([IDL.Nat], [StockUsage], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'recordStockUsage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Nat,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateBranch' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateChecklistItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'updateHall' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateStaff' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateStock' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateVendor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const InvoiceItem = IDL.Record({
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'customerPhone' : IDL.Text,
    'guestCount' : IDL.Nat,
    'createdAt' : Time,
    'menuSelections' : IDL.Vec(IDL.Nat),
    'notes' : IDL.Text,
    'advancePaid' : IDL.Nat,
    'balanceDue' : IDL.Nat,
    'customerId' : IDL.Opt(IDL.Principal),
    'hallId' : IDL.Nat,
    'branchId' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'eventDate' : Time,
    'quotationAmount' : IDL.Nat,
    'eventType' : IDL.Text,
  });
  const Branch = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'managerName' : IDL.Text,
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'assignedTo' : IDL.Nat,
    'task' : IDL.Text,
    'isDone' : IDL.Bool,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'bookingId' : IDL.Nat,
    'submittedAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Hall = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'pricePerHead' : IDL.Nat,
    'description' : IDL.Text,
    'availableSeats' : IDL.Nat,
    'capacity' : IDL.Nat,
    'branchId' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'generatedAt' : Time,
    'isPaid' : IDL.Bool,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(InvoiceItem),
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'assignedTo' : IDL.Nat,
    'interestedHallId' : IDL.Nat,
    'name' : IDL.Text,
    'visitDate' : Time,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const MenuCategory = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isVegetarian' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'method' : IDL.Text,
    'bookingId' : IDL.Nat,
    'notes' : IDL.Text,
    'paymentDate' : Time,
    'paymentType' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Staff = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'branchId' : IDL.Nat,
  });
  const Stock = IDL.Record({
    'id' : IDL.Nat,
    'unit' : IDL.Text,
    'quantityOnHand' : IDL.Nat,
    'itemName' : IDL.Text,
    'minimumThreshold' : IDL.Nat,
    'branchId' : IDL.Nat,
  });
  const StockRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : Time,
    'quantityRequested' : IDL.Nat,
    'itemName' : IDL.Text,
    'branchId' : IDL.Nat,
    'requestedBy' : IDL.Nat,
    'resolvedAt' : IDL.Opt(Time),
    'reason' : IDL.Text,
  });
  const StockUsage = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'stockItemId' : IDL.Nat,
    'recordedAt' : Time,
    'quantityUsed' : IDL.Nat,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'branchId' : IDL.Nat,
  });
  const BookingVendor = IDL.Record({
    'bookingId' : IDL.Nat,
    'vendorId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'branchId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookingVendor' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveStockRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Nat,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createBranch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createChecklistItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createHall' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Nat, IDL.Vec(InvoiceItem), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createMenuCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createStaff' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createStock' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createStockRequest' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createVendor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [], []),
    'deleteChecklistItem' : IDL.Func([IDL.Nat], [], []),
    'deleteHall' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteStaff' : IDL.Func([IDL.Nat], [], []),
    'deleteStock' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getAllChecklistItems' : IDL.Func([], [IDL.Vec(ChecklistItem)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllHalls' : IDL.Func([], [IDL.Vec(Hall)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getAllStock' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
    'getAllStockRequests' : IDL.Func([], [IDL.Vec(StockRequest)], ['query']),
    'getAllStockUsage' : IDL.Func([], [IDL.Vec(StockUsage)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingVendors' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BookingVendor)],
        ['query'],
      ),
    'getBranch' : IDL.Func([IDL.Nat], [Branch], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChecklistItem' : IDL.Func([IDL.Nat], [ChecklistItem], ['query']),
    'getFeedback' : IDL.Func([IDL.Nat], [Feedback], ['query']),
    'getHall' : IDL.Func([IDL.Nat], [Hall], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getMenuCategory' : IDL.Func([IDL.Text], [MenuCategory], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
    'getStaff' : IDL.Func([IDL.Nat], [Staff], ['query']),
    'getStock' : IDL.Func([IDL.Nat], [Stock], ['query']),
    'getStockRequest' : IDL.Func([IDL.Nat], [StockRequest], ['query']),
    'getStockUsage' : IDL.Func([IDL.Nat], [StockUsage], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'recordStockUsage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Nat,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateBranch' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateChecklistItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'updateHall' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateStaff' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateStock' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateVendor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };