/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StockUsage {
    id: bigint;
    bookingId: bigint;
    stockItemId: bigint;
    recordedAt: Time;
    quantityUsed: bigint;
}
export interface InvoiceItem {
    description: string;
    amount: bigint;
}
export interface Hall {
    id: bigint;
    name: string;
    pricePerHead: bigint;
    description: string;
    availableSeats: bigint;
    capacity: bigint;
    branchId: bigint;
}
export type Time = bigint;
export interface MenuCategory {
    name: string;
    description: string;
}
export interface Feedback {
    id: bigint;
    customerName: string;
    bookingId: bigint;
    submittedAt: Time;
    comment: string;
    rating: bigint;
}
export interface BookingVendor {
    bookingId: bigint;
    vendorId: bigint;
}
export interface Payment {
    id: bigint;
    method: string;
    bookingId: bigint;
    notes: string;
    paymentDate: Time;
    paymentType: string;
    amount: bigint;
}
export interface Invoice {
    id: bigint;
    bookingId: bigint;
    generatedAt: Time;
    isPaid: boolean;
    totalAmount: bigint;
    items: Array<InvoiceItem>;
}
export interface Lead {
    id: bigint;
    status: string;
    assignedTo: bigint;
    interestedHallId: bigint;
    name: string;
    visitDate: Time;
    email: string;
    notes: string;
    phone: string;
    eventType: string;
}
export interface MenuItem {
    id: bigint;
    name: string;
    description: string;
    isVegetarian: boolean;
    category: string;
    price: bigint;
}
export interface StockRequest {
    id: bigint;
    status: string;
    createdAt: Time;
    quantityRequested: bigint;
    itemName: string;
    branchId: bigint;
    requestedBy: bigint;
    resolvedAt?: Time;
    reason: string;
}
export interface Staff {
    id: bigint;
    name: string;
    role: string;
    isActive: boolean;
    email: string;
    phone: string;
    branchId: bigint;
}
export interface Stock {
    id: bigint;
    unit: string;
    quantityOnHand: bigint;
    itemName: string;
    minimumThreshold: bigint;
    branchId: bigint;
}
export interface ChecklistItem {
    id: bigint;
    bookingId: bigint;
    assignedTo: bigint;
    task: string;
    isDone: boolean;
}
export interface Branch {
    id: bigint;
    name: string;
    phone: string;
    location: string;
    managerName: string;
}
export interface Booking {
    id: bigint;
    customerName: string;
    status: string;
    paymentStatus: string;
    customerPhone: string;
    guestCount: bigint;
    createdAt: Time;
    menuSelections: Array<bigint>;
    notes: string;
    advancePaid: bigint;
    balanceDue: bigint;
    customerId?: Principal;
    hallId: bigint;
    branchId: bigint;
    customerEmail: string;
    eventDate: Time;
    quotationAmount: bigint;
    eventType: string;
}
export interface Vendor {
    id: bigint;
    serviceType: string;
    name: string;
    email: string;
    phone: string;
    branchId: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
    phone: string;
    branchId?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBookingVendor(bookingId: bigint, vendorId: bigint): Promise<void>;
    approveStockRequest(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmBooking(id: bigint): Promise<void>;
    createBooking(customerName: string, customerPhone: string, customerEmail: string, eventType: string, hallId: bigint, branchId: bigint, eventDate: Time, guestCount: bigint, menuSelections: Array<bigint>, notes: string): Promise<bigint>;
    createBranch(name: string, location: string, managerName: string, phone: string): Promise<bigint>;
    createChecklistItem(bookingId: bigint, task: string, assignedTo: bigint): Promise<bigint>;
    createHall(branchId: bigint, name: string, capacity: bigint, availableSeats: bigint, description: string, pricePerHead: bigint): Promise<bigint>;
    createInvoice(bookingId: bigint, items: Array<InvoiceItem>, totalAmount: bigint): Promise<bigint>;
    createLead(name: string, phone: string, email: string, eventType: string, interestedHallId: bigint, visitDate: Time, notes: string, assignedTo: bigint): Promise<bigint>;
    createMenuCategory(name: string, description: string): Promise<void>;
    createMenuItem(category: string, name: string, description: string, price: bigint, isVegetarian: boolean): Promise<bigint>;
    createStaff(name: string, role: string, branchId: bigint, phone: string, email: string): Promise<bigint>;
    createStock(branchId: bigint, itemName: string, unit: string, quantityOnHand: bigint, minimumThreshold: bigint): Promise<bigint>;
    createStockRequest(branchId: bigint, requestedBy: bigint, itemName: string, quantityRequested: bigint, reason: string): Promise<bigint>;
    createVendor(name: string, serviceType: string, phone: string, email: string, branchId: bigint): Promise<bigint>;
    deleteBooking(id: bigint): Promise<void>;
    deleteBranch(id: bigint): Promise<void>;
    deleteChecklistItem(id: bigint): Promise<void>;
    deleteHall(id: bigint): Promise<void>;
    deleteLead(id: bigint): Promise<void>;
    deleteMenuItem(id: bigint): Promise<void>;
    deleteStaff(id: bigint): Promise<void>;
    deleteStock(id: bigint): Promise<void>;
    deleteVendor(id: bigint): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllBranches(): Promise<Array<Branch>>;
    getAllChecklistItems(): Promise<Array<ChecklistItem>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllHalls(): Promise<Array<Hall>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllMenuCategories(): Promise<Array<MenuCategory>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllStaff(): Promise<Array<Staff>>;
    getAllStock(): Promise<Array<Stock>>;
    getAllStockRequests(): Promise<Array<StockRequest>>;
    getAllStockUsage(): Promise<Array<StockUsage>>;
    getAllVendors(): Promise<Array<Vendor>>;
    getBooking(id: bigint): Promise<Booking>;
    getBookingVendors(bookingId: bigint): Promise<Array<BookingVendor>>;
    getBranch(id: bigint): Promise<Branch>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChecklistItem(id: bigint): Promise<ChecklistItem>;
    getFeedback(id: bigint): Promise<Feedback>;
    getHall(id: bigint): Promise<Hall>;
    getInvoice(id: bigint): Promise<Invoice>;
    getLead(id: bigint): Promise<Lead>;
    getMenuCategory(name: string): Promise<MenuCategory>;
    getMenuItem(id: bigint): Promise<MenuItem>;
    getPayment(id: bigint): Promise<Payment>;
    getStaff(id: bigint): Promise<Staff>;
    getStock(id: bigint): Promise<Stock>;
    getStockRequest(id: bigint): Promise<StockRequest>;
    getStockUsage(id: bigint): Promise<StockUsage>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendor(id: bigint): Promise<Vendor>;
    isCallerAdmin(): Promise<boolean>;
    recordPayment(bookingId: bigint, amount: bigint, paymentType: string, method: string, notes: string): Promise<bigint>;
    recordStockUsage(bookingId: bigint, stockItemId: bigint, quantityUsed: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitFeedback(bookingId: bigint, customerName: string, rating: bigint, comment: string): Promise<bigint>;
    updateBooking(id: bigint, customerName: string, customerPhone: string, customerEmail: string, eventType: string, hallId: bigint, branchId: bigint, eventDate: Time, guestCount: bigint, menuSelections: Array<bigint>, status: string, paymentStatus: string, quotationAmount: bigint, advancePaid: bigint, balanceDue: bigint, notes: string): Promise<void>;
    updateBranch(id: bigint, name: string, location: string, managerName: string, phone: string): Promise<void>;
    updateChecklistItem(id: bigint, task: string, isDone: boolean, assignedTo: bigint): Promise<void>;
    updateHall(id: bigint, branchId: bigint, name: string, capacity: bigint, availableSeats: bigint, description: string, pricePerHead: bigint): Promise<void>;
    updateLead(id: bigint, name: string, phone: string, email: string, eventType: string, interestedHallId: bigint, visitDate: Time, status: string, notes: string, assignedTo: bigint): Promise<void>;
    updateMenuItem(id: bigint, category: string, name: string, description: string, price: bigint, isVegetarian: boolean): Promise<void>;
    updateStaff(id: bigint, name: string, role: string, branchId: bigint, phone: string, email: string, isActive: boolean): Promise<void>;
    updateStock(id: bigint, branchId: bigint, itemName: string, unit: string, quantityOnHand: bigint, minimumThreshold: bigint): Promise<void>;
    updateVendor(id: bigint, name: string, serviceType: string, phone: string, email: string, branchId: bigint): Promise<void>;
}
import type { Booking as _Booking, StockRequest as _StockRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBookingVendor(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookingVendor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookingVendor(arg0, arg1);
            return result;
        }
    }
    async approveStockRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveStockRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveStockRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: Time, arg7: bigint, arg8: Array<bigint>, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createBranch(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBranch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBranch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createChecklistItem(arg0: bigint, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChecklistItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChecklistItem(arg0, arg1, arg2);
            return result;
        }
    }
    async createHall(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHall(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHall(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: Array<InvoiceItem>, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2);
            return result;
        }
    }
    async createLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Time, arg6: string, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createMenuCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuCategory(arg0, arg1);
            return result;
        }
    }
    async createMenuItem(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuItem(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuItem(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createStaff(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createStock(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStock(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStock(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createStockRequest(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStockRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStockRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createVendor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteBranch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteChecklistItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChecklistItem(arg0);
            return result;
        }
    }
    async deleteHall(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHall(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async deleteStock(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStock(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBranches();
            return result;
        }
    }
    async getAllChecklistItems(): Promise<Array<ChecklistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChecklistItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChecklistItems();
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAllHalls(): Promise<Array<Hall>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHalls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHalls();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return result;
        }
    }
    async getAllMenuCategories(): Promise<Array<MenuCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuCategories();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getAllStock(): Promise<Array<Stock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStock();
            return result;
        }
    }
    async getAllStockRequests(): Promise<Array<StockRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStockRequests();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStockRequests();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStockUsage(): Promise<Array<StockUsage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStockUsage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStockUsage();
            return result;
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingVendors(arg0: bigint): Promise<Array<BookingVendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingVendors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingVendors(arg0);
            return result;
        }
    }
    async getBranch(arg0: bigint): Promise<Branch> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranch(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChecklistItem(arg0: bigint): Promise<ChecklistItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChecklistItem(arg0);
            return result;
        }
    }
    async getFeedback(arg0: bigint): Promise<Feedback> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedback(arg0);
            return result;
        }
    }
    async getHall(arg0: bigint): Promise<Hall> {
        if (this.processError) {
            try {
                const result = await this.actor.getHall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHall(arg0);
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return result;
        }
    }
    async getLead(arg0: bigint): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return result;
        }
    }
    async getMenuCategory(arg0: string): Promise<MenuCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuCategory(arg0);
            return result;
        }
    }
    async getMenuItem(arg0: bigint): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return result;
        }
    }
    async getPayment(arg0: bigint): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return result;
        }
    }
    async getStaff(arg0: bigint): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff(arg0);
            return result;
        }
    }
    async getStock(arg0: bigint): Promise<Stock> {
        if (this.processError) {
            try {
                const result = await this.actor.getStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStock(arg0);
            return result;
        }
    }
    async getStockRequest(arg0: bigint): Promise<StockRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockRequest(arg0);
                return from_candid_StockRequest_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockRequest(arg0);
            return from_candid_StockRequest_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockUsage(arg0: bigint): Promise<StockUsage> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockUsage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockUsage(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: bigint): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordPayment(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async recordStockUsage(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStockUsage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStockUsage(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFeedback(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBooking(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: Time, arg8: bigint, arg9: Array<bigint>, arg10: string, arg11: string, arg12: bigint, arg13: bigint, arg14: bigint, arg15: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            return result;
        }
    }
    async updateBranch(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateChecklistItem(arg0: bigint, arg1: string, arg2: boolean, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChecklistItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChecklistItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHall(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHall(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHall(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Time, arg7: string, arg8: string, arg9: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateStaff(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateStock(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStock(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStock(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateVendor(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_Booking_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_StockRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockRequest): StockRequest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    email: string;
    phone: string;
    branchId: [] | [bigint];
}): {
    name: string;
    role: string;
    email: string;
    phone: string;
    branchId?: bigint;
} {
    return {
        name: value.name,
        role: value.role,
        email: value.email,
        phone: value.phone,
        branchId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.branchId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: string;
    paymentStatus: string;
    customerPhone: string;
    guestCount: bigint;
    createdAt: _Time;
    menuSelections: Array<bigint>;
    notes: string;
    advancePaid: bigint;
    balanceDue: bigint;
    customerId: [] | [Principal];
    hallId: bigint;
    branchId: bigint;
    customerEmail: string;
    eventDate: _Time;
    quotationAmount: bigint;
    eventType: string;
}): {
    id: bigint;
    customerName: string;
    status: string;
    paymentStatus: string;
    customerPhone: string;
    guestCount: bigint;
    createdAt: Time;
    menuSelections: Array<bigint>;
    notes: string;
    advancePaid: bigint;
    balanceDue: bigint;
    customerId?: Principal;
    hallId: bigint;
    branchId: bigint;
    customerEmail: string;
    eventDate: Time;
    quotationAmount: bigint;
    eventType: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        paymentStatus: value.paymentStatus,
        customerPhone: value.customerPhone,
        guestCount: value.guestCount,
        createdAt: value.createdAt,
        menuSelections: value.menuSelections,
        notes: value.notes,
        advancePaid: value.advancePaid,
        balanceDue: value.balanceDue,
        customerId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.customerId)),
        hallId: value.hallId,
        branchId: value.branchId,
        customerEmail: value.customerEmail,
        eventDate: value.eventDate,
        quotationAmount: value.quotationAmount,
        eventType: value.eventType
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    createdAt: _Time;
    quantityRequested: bigint;
    itemName: string;
    branchId: bigint;
    requestedBy: bigint;
    resolvedAt: [] | [_Time];
    reason: string;
}): {
    id: bigint;
    status: string;
    createdAt: Time;
    quantityRequested: bigint;
    itemName: string;
    branchId: bigint;
    requestedBy: bigint;
    resolvedAt?: Time;
    reason: string;
} {
    return {
        id: value.id,
        status: value.status,
        createdAt: value.createdAt,
        quantityRequested: value.quantityRequested,
        itemName: value.itemName,
        branchId: value.branchId,
        requestedBy: value.requestedBy,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.resolvedAt)),
        reason: value.reason
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockRequest>): Array<StockRequest> {
    return value.map((x)=>from_candid_StockRequest_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    email: string;
    phone: string;
    branchId?: bigint;
}): {
    name: string;
    role: string;
    email: string;
    phone: string;
    branchId: [] | [bigint];
} {
    return {
        name: value.name,
        role: value.role,
        email: value.email,
        phone: value.phone,
        branchId: value.branchId ? candid_some(value.branchId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
